 
before_script:

.build-template:
  image: forthy42/gforth-builder-linux-$ARCH:$DISTRIBUTION
  script:
    - ./autogen.sh
    - case $ARCH in
      i386)
        export BARCH=i686-pc-linux-gnu
        ;;
      amd64)
        export BARCH=x86_64-pc-linux-gnu
        ;;
      arm64)
        export BARCH=aarch64-pc-linux-gnu
        ;;
      armel)
        export BARCH=arm-pc-linux-gnueabi
        ;;
      armhf)
        export BARCH=arm-pc-linux-gnueabihf
        ;;
      esac
    - ./configure --with-extra-libs --host=$BARCH --build=$BARCH
    - make distclean
    - dpkg-buildpackage -uc -us -d -b -j1 -a$ARCH
    - mkdir -p debian/$DISTRIBUTION/$ARCH
    - rm -f debian/$DISTRIBUTION/$ARCH/*.deb
    - mv ../*.deb debian/$DISTRIBUTION/$ARCH/
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - debian/$DISTRIBUTION/$ARCH/*.deb

build:
  extends: .build-template
  parallel:
    matrix:
      - DISTRIBUTION: [unstable, stable, oldstable]
        ARCH: [amd64, i386]
